#!/bin/sh

if [ $# -lt 1 ]
then
	echo "Usage: formatDataToLibsvm <in.txt> <out.txt>"
else
    if [ x$2 != x ]
    then
        out=$2
    else
        out=${1}.data
    fi
	awk '{printf $1; for (i = 2; i <= NF; ++i){ printf "\t"i-1":"$i ;} printf "\n";}' $1 > $out
fi
